### ISSUE TITLE
Error with bgaw build --deploy : Invalid working directory specified,  does not exist

### ISSUE THREAD

**Issue by Lucas-C** [danielholmes/bga-workbench#1]
Hi !

Thanks for developping this workbench :)

I'm trying to use it and I got the following error:
```
$ composer exec bgawb -v -- build -d


  [RuntimeException]
  Invalid working directory specified,  does not exist.


Exception trace:
 () at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:276
 Composer\Console\Application->getNewWorkingDir() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:114
 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:127
 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:54
 require() at C:\ProgramData\ComposerSetup\bin\composer.phar:24
```

I suspect I should create some configuration file, but I haven't found any indications on how to do so and what it should look like.

Could you please me with this error message ?

**Comment by Lucas-C** [comment]
Thanks for you quick & helpful answer !

With a friend, @ntaffore, we started working on our very first BGA game, https://github.com/Lucas-C/tablut, and it basically started as a fork of your battle-for-hill-218 project.

It's great that you added unit tests ! It seems a bit complicated to test a BGA game code given the framework architecture.

I understand now where the error comes from. And you remade `bgaproject.yml.dist` into `bgaproject.yml` in your project :)

I'll let you now if I find a workaround for the `composer exec` issue

**Comment by danielholmes** [comment]
This definitely looks like an issue in Symfony - not composer. But it's also supposed to have been fixed. See [https://github.com/composer/composer/issues/5377](https://github.com/composer/composer/issues/5377) and [https://github.com/symfony/symfony/pull/11431](https://github.com/symfony/symfony/pull/11431).

Another workaround is to use the long version of the flag instead: `--deploy` (I haven't tested that but in theory it should get around the issue).

> With a friend, @ntaffore, we started working on our very first BGA game, https://github.com/Lucas-C/tablut, and it basically started as a fork of your battle-for-hill-218 project.

Cool! Good luck with it

> It's great that you added unit tests ! It seems a bit complicated to test a BGA game code given the framework architecture.

Yes... It took a while for me to work out. Having the tests helped out the project so much.

> I understand now where the error comes from. And you remade bgaproject.yml.dist into bgaproject.yml in your project :)

The reason for that is I didn't want my production username and password in the repo - since you're using the deploy functionality you'll have to find some way around that too I guess.

> I'll let you now if I find a workaround for the composer exec issue

That would be great, thank you


Thanks for raising the issue. Please don't hesitate to reach out if you have any others - it will help me for writing the documentation

**Comment by Lucas-C** [comment]
Actually I think this is more of a Windows-related issue :(

When I run:
```
vendor\bin\bgawb -v build --deploy
```

I get the following error:
```
'classpreloader.php' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
```

Which can be translated from French to English as:
```
'classpreloader.php' is not recognized as an internal or external command,
an executable program or a commands file.
```

This comes from this code:
https://github.com/danielholmes/bga-workbench/blob/master/src/BGAWorkbench/Builder/CompileComposerGame.php#L132

I think expecting `classpreloader.php` to be executable is to ask for Windows... :(
I tried to postpone this `ProcessBuilder::create` array of process arguments with `php`, but then I got:
```
Could not open input file: classpreloader.php
```

**Comment by danielholmes** [comment]
Hmm okay. Maybe it requires running through `composer exec` then - since composer/bin should be within the path, which is where classpreloader.php is. With the long flag names (--deploy --watch) it should work okay.

I've updated this package to prepend with php as you've done (so try updating to 0.0.7), since it looks like it won't work on Windows at all without that.

**Comment by Lucas-C** [comment]
TYVM for trying to find a fix !

**Comment by danielholmes** [comment]
@Lucas-C I've removed the Process usage for compiling in version `0.0.9`. So please grab an update and let me know how that part goes

**Comment by Lucas-C** [comment]
Works perfectly, thanks !
