### ISSUE TITLE
bgaw build fail due to post-install-cmd

### ISSUE THREAD

**Issue by Lucas-C** [danielholmes/bga-workbench#5]
Hi.

Here is an example of failing output in TravisCI:
https://travis-ci.org/Lucas-C/tablut/builds/353327763

```$ vendor/bin/bgawb -v build
The command "'composer' 'install' '--no-dev' '-o' '-d' '/home/travis/build/Lucas-C/tablut/build/prod-vendors'" failed.
Exit Code: 127(Command not found)
Working directory: /home/travis/build/Lucas-C/tablut
Output:
================
Error Output:
================
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 2 installs, 0 updates, 0 removals
  - Installing lstrojny/functional-php (1.6.0): Loading from cache
  - Installing phpoption/phpoption (1.5.0): Loading from cache
Generating optimized autoload files
> phpcs --config-set installed_paths vendor/wimg/php-compatibility
sh: 1: phpcs: not found
Script phpcs --config-set installed_paths vendor/wimg/php-compatibility handling the post-install-cmd event returned with error code 127
The command "vendor/bin/bgawb -v build" exited with 255.
```
I found the related code, but don't know how to work around this issue:
https://github.com/danielholmes/bga-workbench/blob/master/src/BGAWorkbench/Builder/CompileComposerGame.php#L344

The `post-install-cmd` I use:
https://github.com/Lucas-C/tablut/blob/master/composer.json#L45

**Comment by Lucas-C** [comment]
Note than on my Windows computer it works perfectly well

**Comment by danielholmes** [comment]
@Lucas-C It looks like it can't find the phpcs binary:

`sh: 1: phpcs: not found`

You've got it specified correctly as a dev dependency. The problem is that bgawb creates a production copy of your dependencies (so no dev dependencies) via a special composer install, which then triggers your script.

I can see 2 possible solutions:

1. In that composer install of production deps, also include the `--no-scripts` option so it will never run these event scripts
2. You write some logic in your event scripts to only run when phpcs is available/the composer environment is the dev one

I prefer 1, although i can imagine some future cases where you'd want these post install hooks even for setting up production dependencies. Let me know what you think.

P.S. I'm not sure why it works on your windows machine - maybe you have a phpcs binary in the global environment path somewhere. e.g. globally installed with PHP

**Comment by Lucas-C** [comment]
Solution 1. looks the best to me.

Thanks for taking the time to have a look and figure this out !

PS: yeah, that's what I thought too, but no I don't have a `phpcs` command in my `%PATH%` ! But uou're right, and maybe `composer` `%PATH%` is slighlty different and use a `phpcs` somewhere.

**Comment by danielholmes** [comment]
@Lucas-C Released a new version with this change here: https://github.com/danielholmes/bga-workbench/releases/tag/v0.1.0 let me know how it goes for you

**Comment by Lucas-C** [comment]
Thank you !
That fixed my issue :)
